eureka:
  client:
    service-url:
      defaultZone: ${discovery.client.url}
server:
  port: 8003
spring:
  cloud:
    gateway:
      routes:
      - id: hello-service
        uri: lb://REST
        predicates:
        - Path=/hello 